plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/mattes/Library/CloudStorage/Dropbox/KI RND/Wibs Webseite/CLAUDE_CODE_VARIANTE"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]